version: "3.8"

services:
  postgres:
    image: postgres:16.3
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: restaurantdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  restaurant-management:
    image: docker.io/thisissvikas/restaurant-management:latest
    depends_on:
      postgres:
        condition: service_healthy
    profiles: ["e2e"]
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/restaurantdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  postgres_data:
