spring:
  application:
    name: restaurant-management
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurantdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    default_schema: restaurant_management

server:
  servlet:
    context-path: /api
  port: 8080