name: Build

on:
  pull_request:
    branches:
      - main
  schedule:
  # every night
  - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('restaurant-management/**/*.gradle*', 'restaurant-management/**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x restaurant-management/gradlew

      - name: Build with Gradle
        run: ./restaurant-management/gradlew clean build
